[package]
name = "gf_samples"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
gf_base = { path = "../base"}
pollster = "0.3.0"
bytemuck = {version = "1.13.1",  features = [ "derive" ]}